package generator_uml.back_generator_uml.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.github.mustachejava.DefaultMustacheFactory;
import generator_uml.back_generator_uml.entity.UmlAttribute;
import generator_uml.back_generator_uml.entity.UmlClass;
import generator_uml.back_generator_uml.entity.UmlRelationship;
import generator_uml.back_generator_uml.entity.UmlSchema;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.zeroturnaround.zip.ZipUtil;

import java.io.ByteArrayOutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

/**
 * Physically proves that a project produced by {@link ProjectGenerator} compiles, by generating
 * a representative schema (two plain entities, a 1:N relationship and an N:M relationship that
 * forces a synthesized join entity), extracting the resulting zip into a temp directory, and
 * running the real generated project's own pom.xml through Maven with tests skipped.
 *
 * <p>Nothing generated by this test is written into the repository; both the generator's temp
 * output and the extraction directory live under the OS temp directory.
 */
class ProjectGeneratorCompileTest {

    @Test
    @Timeout(value = 6, unit = TimeUnit.MINUTES)
    void generatedProjectCompilesAndPostmanCollectionMatches() throws Exception {
        UmlSchema schema = buildSampleSchema();

        ProjectGenerator projectGenerator =
                new ProjectGenerator(new DefaultMustacheFactory(), new PostmanCollectionGenerator());

        Path zip = projectGenerator.generate(schema, "com.example.compilecheck", "compile-check-app");
        assertTrue(Files.exists(zip), "Generated project zip should exist");

        Path extractDir = Files.createTempDirectory("compile-check-extract-");
        ZipUtil.unpack(zip.toFile(), extractDir.toFile());

        Path pom = extractDir.resolve("pom.xml");
        assertTrue(Files.exists(pom), "Generated project must contain a pom.xml");

        int exitCode = runMavenPackage(pom);
        assertEquals(0, exitCode, "Generated Spring Boot project must compile via 'mvn package -DskipTests'");

        verifyPostmanCollection(extractDir);
    }

    /**
     * Regression coverage for two bugs found by manual audit:
     * <ul>
     *   <li>BUG 1: a class with no numeric/String/char attribute (e.g. only {@code boolean}/
     *       {@code double}) had no eligible primary key, leaving Repository.mustache to render
     *       {@code JpaRepository<Producto, >} — invalid Java.</li>
     *   <li>BUG 2: a class whose primary key is {@code String} (first attribute is a string,
     *       e.g. {@code idUsuario}) participating in a relationship caused the *other* side's
     *       generated Service/Controller to declare {@code findUsuarioById(Long id)} instead of
     *       {@code findUsuarioById(String id)} — a type mismatch against
     *       {@code JpaRepository<Usuario, String>}.
     * </ul>
     * Both are exercised together and the resulting project is actually compiled with Maven.
     */
    @Test
    @Timeout(value = 6, unit = TimeUnit.MINUTES)
    void generatedProjectWithMissingPkAndStringPkCompiles() throws Exception {
        // Producto: sin atributo elegible como PK (nombre:string SÍ sería elegible, así que
        // se usa solo double/boolean para forzar el fallback de PK sintética).
        UmlClass producto = umlClass("producto", "Producto",
                attr("precio", "double"), attr("activo", "boolean"));

        // Usuario: PK real de tipo String (idUsuario es el primer atributo).
        UmlClass usuario = umlClass("usuario", "Usuario",
                attr("idUsuario", "string"), attr("nombre", "string"));

        // Pedido: PK Long normal, con ManyToOne hacia Usuario (PK String).
        UmlClass pedido = umlClass("pedido", "Pedido",
                attr("id", "int"), attr("fecha", "string"), attr("total", "double"));

        // Usuario 1 -- * Pedido
        UmlRelationship usuarioToPedido = relationship("r1", "association", "usuario", "pedido", "1", "*");

        UmlSchema schema = new UmlSchema();
        schema.setClasses(List.of(producto, usuario, pedido));
        schema.setRelationships(List.of(usuarioToPedido));

        ProjectGenerator projectGenerator =
                new ProjectGenerator(new DefaultMustacheFactory(), new PostmanCollectionGenerator());

        Path zip = projectGenerator.generate(schema, "com.example.pkcheck", "pk-check-app");
        Path extractDir = Files.createTempDirectory("pk-check-extract-");
        ZipUtil.unpack(zip.toFile(), extractDir.toFile());

        Path modelDir = extractDir.resolve("src/main/java/com/example/pkcheck/model");
        Path repoDir = extractDir.resolve("src/main/java/com/example/pkcheck/repository");
        Path svcDir = extractDir.resolve("src/main/java/com/example/pkcheck/service");

        // BUG 1: Producto debe tener una PK Long sintética, y el repository debe usarla.
        String productoEntity = Files.readString(modelDir.resolve("Producto.java"));
        assertTrue(productoEntity.contains("@GeneratedValue(strategy = GenerationType.IDENTITY)")
                        && productoEntity.contains("private Long id;"),
                "Producto sin PK elegible debe recibir un id Long autogenerado");
        String productoRepo = Files.readString(repoDir.resolve("ProductoRepository.java"));
        assertTrue(productoRepo.contains("JpaRepository<Producto, Long>"),
                "ProductoRepository debe quedar tipado con la PK sintética Long, nunca vacío");

        // BUG 2: PedidoService debe buscar Usuario por String, no por Long.
        String pedidoService = Files.readString(svcDir.resolve("PedidoService.java"));
        assertTrue(pedidoService.contains("findUsuarioById(String id)"),
                "PedidoService debe usar el tipo real de la PK de Usuario (String), no Long");
        assertTrue(!pedidoService.contains("findUsuarioById(Long id)"),
                "PedidoService no debe seguir usando Long para una relación hacia una PK String");

        int exitCode = runMavenPackage(extractDir.resolve("pom.xml"));
        assertEquals(0, exitCode, "El proyecto generado con PK faltante y PK String debe compilar");
    }

    // ===================== schema =====================

    private UmlSchema buildSampleSchema() {
        UmlClass author = umlClass("author", "Author",
                attr("id", "int"), attr("name", "string"), attr("email", "string"));
        UmlClass book = umlClass("book", "Book",
                attr("id", "int"), attr("title", "string"), attr("isbn", "string"));
        UmlClass publisher = umlClass("publisher", "Publisher",
                attr("id", "int"), attr("name", "string"));

        // 1:N -> Publisher 1 -- * Book
        UmlRelationship publisherToBook = relationship("r1", "association", "publisher", "book", "1", "*");
        // N:M -> Author *--* Book, forces an AuthorBook join entity
        UmlRelationship authorToBook = relationship("r2", "association", "author", "book", "*", "*");

        UmlSchema schema = new UmlSchema();
        schema.setClasses(List.of(author, book, publisher));
        schema.setRelationships(List.of(publisherToBook, authorToBook));
        return schema;
    }

    private UmlClass umlClass(String id, String name, UmlAttribute... attributes) {
        UmlClass c = new UmlClass();
        c.setId(id);
        c.setName(name);
        c.setAttributes(new ArrayList<>(List.of(attributes)));
        c.setMethods(new ArrayList<>());
        return c;
    }

    private UmlAttribute attr(String name, String type) {
        UmlAttribute a = new UmlAttribute();
        a.setName(name);
        a.setType(type);
        return a;
    }

    private UmlRelationship relationship(String id, String type, String sourceId, String targetId,
                                          String sourceCard, String targetCard) {
        UmlRelationship r = new UmlRelationship();
        r.setId(id);
        r.setType(type);
        r.setSourceId(sourceId);
        r.setTargetId(targetId);
        r.setLabels(List.of(sourceCard, targetCard));
        return r;
    }

    // ===================== postman verification =====================

    private void verifyPostmanCollection(Path extractDir) throws Exception {
        Path postman = extractDir.resolve("compile-check-app-postman-collection.json");
        assertTrue(Files.exists(postman), "Postman collection file should be present in the generated zip");

        ObjectMapper mapper = new ObjectMapper();
        JsonNode root = mapper.readTree(postman.toFile());
        assertTrue(root.has("item"), "Postman collection must have top-level 'item' folders");

        List<String> folderNames = new ArrayList<>();
        root.get("item").forEach(folder -> folderNames.add(folder.get("name").asText()));

        assertTrue(folderNames.contains("Author"), "Postman collection must contain an Author folder");
        assertTrue(folderNames.contains("Book"), "Postman collection must contain a Book folder");
        assertTrue(folderNames.contains("Publisher"), "Postman collection must contain a Publisher folder");
        assertTrue(folderNames.stream().anyMatch(n -> n.startsWith("AuthorBook")),
                "Postman collection must contain the AuthorBook join-entity folder produced by the N:M relationship");

        for (JsonNode folder : root.get("item")) {
            List<String> requestNames = new ArrayList<>();
            folder.get("item").forEach(req -> requestNames.add(req.get("name").asText()));
            String entity = folder.get("name").asText().replace(" (Relación)", "");

            assertTrue(requestNames.contains("Get All " + entity), "Missing GET all for " + entity);
            assertTrue(requestNames.contains("Get One " + entity), "Missing GET one for " + entity);
            assertTrue(requestNames.contains("Create " + entity), "Missing POST for " + entity);
            assertTrue(requestNames.contains("Update " + entity), "Missing PUT for " + entity);
            assertTrue(requestNames.contains("Delete " + entity), "Missing DELETE for " + entity);
        }
    }

    // ===================== maven invocation =====================

    private int runMavenPackage(Path pom) throws Exception {
        String mvnw = System.getProperty("os.name").toLowerCase().contains("win") ? "mvnw.cmd" : "mvnw";
        Path wrapper = Path.of(System.getProperty("user.dir"), mvnw).toAbsolutePath();
        assertTrue(Files.exists(wrapper), "Maven wrapper not found at " + wrapper);

        ProcessBuilder pb = new ProcessBuilder(
                wrapper.toString(), "-f", pom.toString(), "-B", "-q", "package", "-DskipTests");
        pb.redirectErrorStream(true);
        Process process = pb.start();

        ByteArrayOutputStream output = new ByteArrayOutputStream();
        process.getInputStream().transferTo(output);

        boolean finished = process.waitFor(5, TimeUnit.MINUTES);
        if (!finished) {
            process.destroyForcibly();
            fail("Maven build of the generated project did not finish in time");
        }

        int exitCode = process.exitValue();
        if (exitCode != 0) {
            System.err.println("Generated project build output:\n" + output);
        }
        return exitCode;
    }
}
